LABELS = {
    0: "SELLER_NAME",
    1: "SELLER_NIP",
    2: "BUYER_NAME",
    3: "BUYER_NIP",
    4: "TOTAL_PRICE",
    5: "INVOICE_NUMBER",
    6: "INVOICE_DATE",
    7: "SALE_DATE",
    8: "NET_AMOUNT",
    9: "VAT_AMOUNT",
    10: "CURRENCY",
    11: "OTHER",
}

NUM_CLASSES = len(LABELS)
IMG_SIZE = 128